version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ Broker
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build: ./producer
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer_payments:
    build: ./consumer_payments
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer_analytics:
    build: ./consumer_analytics
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer_shop:
    build: ./consumer_shop
    depends_on:
      rabbitmq:
        condition: service_healthy